# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
    port: 9000

#mysql
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/local_demo
        name: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
#        type: com.alibaba.druid.pool.DruidDataSource


## Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

## mysql
#spring:
#    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/xiaoyaoji?useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: tiger
#    jackson:
#        time-zone: GMT+8
#        date-format: yyyy-MM-dd HH:mm:ss
#    resources:
#            static-locations: classpath:/static/,classpath:/views/
#
## Mybatis配置
#mybatis:
#    mapperLocations: classpath:mapper/**/*.xml
#
